#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=/dev/null
. "$SCRIPT_DIR/lib/config.sh"
load_project_env "$SCRIPT_DIR"

CONFIG_MODE="project"
TARGET_PROJECT="${REMOTE_PILOT_PROJECT:-default}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)
      TARGET_PROJECT="${2:-}"
      shift 2
      ;;
    --global)
      CONFIG_MODE="global"
      shift
      ;;
    *)
      echo "Usage: $0 [--project NAME] [--global]" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$TARGET_PROJECT" ]]; then
  echo "Project name cannot be empty" >&2
  exit 1
fi

BASE_ENV_FILE="$SCRIPT_DIR/.env"
PROJECT_ENV_DIR="$SCRIPT_DIR/projects"
PROJECT_ENV_FILE="$PROJECT_ENV_DIR/${TARGET_PROJECT}.env"
PROJECT_LOCAL_ENV_FILE="$PROJECT_ENV_DIR/${TARGET_PROJECT}.local.env"

prompt_value() {
  local __var_name="$1"
  local prompt_label="$2"
  local default_value="${3:-}"
  local response=""

  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt_label [$default_value]: " response || true
    response="${response:-$default_value}"
  else
    read -r -p "$prompt_label: " response || true
  fi

  printf -v "$__var_name" '%s' "$response"
}

write_setting() {
  local key="$1"
  local value="$2"
  printf '%s=%q\n' "$key" "$value" >> "$ENV_FILE"
}

default_remote="${RCLONE_REMOTE:-gdrive:}"

if [[ "$CONFIG_MODE" == "global" ]]; then
  echo "Remote Pilot global configuration"
  echo "This writes $BASE_ENV_FILE."
  echo

  prompt_value REMOTE_ACCESS_EMAIL_VALUE "Google Drive email to grant access to shared folders" "$REMOTE_ACCESS_EMAIL"
  prompt_value RCLONE_REMOTE_VALUE "Default rclone remote name" "$default_remote"
  prompt_value NOTIFIER_PASSWORD_FILE_VALUE "Default password file for SMTP app password" "$NOTIFIER_PASSWORD_FILE"

  ENV_FILE="$BASE_ENV_FILE"
  : > "$ENV_FILE"
  {
    echo "# Generated by configure.sh on $(date -Is)"
    echo "# Global defaults shared by project instances."
  } >> "$ENV_FILE"
  write_setting "REMOTE_ACCESS_EMAIL" "$REMOTE_ACCESS_EMAIL_VALUE"
  write_setting "REMOTE_PILOT_PROJECT" "$TARGET_PROJECT"
  write_setting "REMOTE_PILOT_PROJECT_ENV_DIR" "$PROJECT_ENV_DIR"
  write_setting "RCLONE_REMOTE" "$RCLONE_REMOTE_VALUE"
  write_setting "NOTIFIER_PASSWORD_FILE" "$NOTIFIER_PASSWORD_FILE_VALUE"
  chmod 600 "$ENV_FILE"

  cat <<EOF

Saved global configuration to $ENV_FILE
Per-project configs live under $PROJECT_ENV_DIR/<project>.env
EOF
  exit 0
fi

default_project_dir="${PROJECT_DIR:-$HOME/projects/$TARGET_PROJECT}"
default_mount="$HOME/remote-pilot/${TARGET_PROJECT}/command-channel"
default_mirror_subdir="${MIRROR_REMOTE_SUBDIR:-${TARGET_PROJECT}/$(hostname -s 2>/dev/null || echo remote-host)}"

echo "Remote Pilot project configuration"
echo "Project name: $TARGET_PROJECT"
echo "This writes $PROJECT_ENV_FILE and creates project runtime directories."
echo "ARC / VT defaults: SMTP sender defaults to arc.knust.job.notifier@gmail.com and the VT secondary recipient defaults to achenie@vt.edu."
echo "Primary recipient has no default and should be set by the user."
echo

prompt_value REMOTE_ACCESS_EMAIL_VALUE "Google Drive email to grant access to the shared folders" "$REMOTE_ACCESS_EMAIL"
prompt_value RCLONE_REMOTE_VALUE "rclone remote name for that Drive account" "$default_remote"
prompt_value PROJECT_DIR_VALUE "Main project directory on the remote system" "$default_project_dir"
prompt_value COMMAND_CHANNEL_FOLDER_ID_VALUE "Google Drive folder ID for the shared command channel" "$COMMAND_CHANNEL_FOLDER_ID"
prompt_value MIRROR_ROOT_FOLDER_ID_VALUE "Google Drive folder ID for the shared mirror root" "$MIRROR_ROOT_FOLDER_ID"
prompt_value COMMAND_CHANNEL_MOUNT_VALUE "Local mount point for the command channel" "$default_mount"
prompt_value MIRROR_REMOTE_SUBDIR_VALUE "Mirror subdirectory name for this machine" "$default_mirror_subdir"
prompt_value SMTP_USER_VALUE "SMTP sender email for optional job notifications" "${SMTP_USER:-arc.knust.job.notifier@gmail.com}"
prompt_value NOTIFICATION_TO_PRIMARY_VALUE "Primary notification recipient (required if using email)" "${NOTIFICATION_TO_PRIMARY:-}"
prompt_value NOTIFICATION_TO_SECONDARY_VALUE "Secondary notification recipient" "${NOTIFICATION_TO_SECONDARY:-achenie@vt.edu}"
prompt_value NOTIFIER_PASSWORD_FILE_VALUE "Password file for SMTP app password" "$NOTIFIER_PASSWORD_FILE"

PROJECT_INSTANCE_ROOT_VALUE="${PROJECT_DIR_VALUE}/.remote-pilot/${TARGET_PROJECT}"
mkdir -p "$COMMAND_CHANNEL_MOUNT_VALUE" "$PROJECT_INSTANCE_ROOT_VALUE/logs" "$PROJECT_INSTANCE_ROOT_VALUE/state" "$PROJECT_ENV_DIR"

ENV_FILE="$PROJECT_ENV_FILE"
: > "$ENV_FILE"
{
  echo "# Generated by configure.sh on $(date -Is)"
  echo "# Project-specific config for REMOTE_PILOT_PROJECT=$TARGET_PROJECT"
} >> "$ENV_FILE"
write_setting "PROJECT_NAME" "$TARGET_PROJECT"
write_setting "REMOTE_ACCESS_EMAIL" "$REMOTE_ACCESS_EMAIL_VALUE"
write_setting "PROJECT_DIR" "$PROJECT_DIR_VALUE"
write_setting "PROJECT_INSTANCE_ROOT" "$PROJECT_INSTANCE_ROOT_VALUE"
write_setting "RCLONE_REMOTE" "$RCLONE_REMOTE_VALUE"
write_setting "COMMAND_CHANNEL_FOLDER_ID" "$COMMAND_CHANNEL_FOLDER_ID_VALUE"
write_setting "COMMAND_CHANNEL_MOUNT" "$COMMAND_CHANNEL_MOUNT_VALUE"
write_setting "COMMAND_FILE_NAME" "commands.sh"
write_setting "COMMAND_CHANNEL_LOG_SUBDIR" "logs"
write_setting "MIRROR_ROOT_FOLDER_ID" "$MIRROR_ROOT_FOLDER_ID_VALUE"
write_setting "MIRROR_REMOTE_SUBDIR" "$MIRROR_REMOTE_SUBDIR_VALUE"
write_setting "SYNC_SOURCE_DIR" "$PROJECT_DIR_VALUE"
write_setting "SLEEP_SECS" "$SLEEP_SECS"
write_setting "TTL_HOURS" "$TTL_HOURS"
write_setting "RUN_IN_BACKGROUND" "$RUN_IN_BACKGROUND"
write_setting "MAX_CONCURRENT" "$MAX_CONCURRENT"
write_setting "COMMAND_TIMEOUT_SECS" "$COMMAND_TIMEOUT_SECS"
write_setting "COMMAND_TIMEOUT_KILL_GRACE_SECS" "$COMMAND_TIMEOUT_KILL_GRACE_SECS"
write_setting "TIMEOUT_REQUEUE_TO_BG" "$TIMEOUT_REQUEUE_TO_BG"
write_setting "PUBLISH_LOGS" "$PUBLISH_LOGS"
write_setting "SMTP_USER" "$SMTP_USER_VALUE"
write_setting "NOTIFICATION_TO_PRIMARY" "$NOTIFICATION_TO_PRIMARY_VALUE"
write_setting "NOTIFICATION_TO_SECONDARY" "$NOTIFICATION_TO_SECONDARY_VALUE"
write_setting "NOTIFIER_PASSWORD_FILE" "$NOTIFIER_PASSWORD_FILE_VALUE"
chmod 600 "$ENV_FILE"

cat <<EOF

Saved project configuration to $ENV_FILE

Optional machine-only overrides can be placed in:
  $PROJECT_LOCAL_ENV_FILE

Next steps:
1. Select the project instance:
   export REMOTE_PILOT_PROJECT=$TARGET_PROJECT
2. Confirm your rclone remote can see the shared folders:
   rclone lsd ${RCLONE_REMOTE_VALUE}
3. Start the relay:
   ./relayctl.sh start
4. Mirror project outputs back to Drive when needed:
   ./sync_mirror.sh
EOF
